# Generated by Django 4.2.3 on 2025-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_profile_picture_tfoiel.webp', upload_to='images/'),
        ),
    ]
