# Generated by Django 5.1.5 on 2025-02-03 00:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='../default_profile_picture_tfoiel', max_length=255, verbose_name='image'),
        ),
    ]
